site_name: PyCon TW post-event report generator (rg-cli)
nav:
  - Home: index.md
  - Contribute: contribute.md
theme:
  name: 'material'
repo_url: https://github.com/pycontw/pycontw-postevent-report-generator
remote_branch: gh-pages
remote_name: origin
